# Generated by Django 2.1.5 on 2019-01-24 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('data_implantacao', models.DateField()),
                ('ultima_atualizacao', models.DateField(blank=True)),
                ('valor', models.IntegerField(blank=True)),
                ('periodo', models.CharField(max_length=30)),
                ('observacoes', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Assinatura',
            },
        ),
        migrations.CreateModel(
            name='DiasSemana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dia', models.IntegerField(default=0)),
                ('dia', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': '[fixo] Dias da Semana',
            },
        ),
        migrations.CreateModel(
            name='IntervalosHorarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalo', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': '[fixo] Intervalos de Horários',
            },
        ),
        migrations.CreateModel(
            name='Permissoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Permissões',
            },
        ),
        migrations.CreateModel(
            name='TipoFuncionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=200)),
                ('permissoes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios_espaco.Permissoes')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Funcionários',
            },
        ),
        migrations.CreateModel(
            name='UsuarioEspaco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=50)),
                ('endereco', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('telefone_celular', models.CharField(max_length=30)),
                ('telefone_residencial', models.CharField(blank=True, max_length=30)),
                ('telefone_comercial', models.CharField(blank=True, max_length=30)),
                ('cpf', models.CharField(max_length=30)),
                ('rg', models.CharField(max_length=30)),
                ('foto', models.ImageField(blank=True, upload_to='fotos_usuarios_espaco')),
                ('apelido', models.CharField(blank=True, max_length=30)),
                ('nome_contato_emergencia', models.CharField(blank=True, max_length=50)),
                ('telefone_contato_emergencia', models.CharField(blank=True, max_length=30)),
                ('tem_plano_saude', models.BooleanField(default=False)),
                ('nome_plano_saude', models.CharField(blank=True, max_length=50)),
                ('dias_provaveis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios_espaco.DiasSemana')),
                ('horarios_provaveis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios_espaco.IntervalosHorarios')),
                ('tipo_assinatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios_espaco.Assinatura')),
                ('tipo_funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios_espaco.TipoFuncionario')),
            ],
            options={
                'verbose_name_plural': 'Usuários do Espaço',
            },
        ),
        migrations.AddField(
            model_name='assinatura',
            name='permissoes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios_espaco.Permissoes'),
        ),
    ]
