# Generated by Django 2.1.5 on 2019-01-24 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_espaco', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assinatura',
            old_name='observacoes',
            new_name='observacao',
        ),
    ]
