# Generated by Django 2.1.5 on 2019-01-28 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrativo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioDiasSemana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dias_provaveis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrativo.DiasSemana')),
            ],
            options={
                'verbose_name': 'Provável Dia de Uso',
                'verbose_name_plural': 'Prováveis Dias de Uso',
            },
        ),
        migrations.CreateModel(
            name='UsuarioEspaco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=50)),
                ('endereco', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('telefone_celular', models.CharField(max_length=30)),
                ('telefone_residencial', models.CharField(blank=True, max_length=30)),
                ('telefone_comercial', models.CharField(blank=True, max_length=30)),
                ('cpf', models.CharField(max_length=30)),
                ('rg', models.CharField(max_length=30)),
                ('foto', models.ImageField(blank=True, upload_to='fotos_usuarios_espaco')),
                ('apelido', models.CharField(blank=True, max_length=30)),
                ('nome_contato_emergencia', models.CharField(blank=True, max_length=50)),
                ('telefone_contato_emergencia', models.CharField(blank=True, max_length=30)),
                ('tem_plano_saude', models.BooleanField(default=False)),
                ('nome_plano_saude', models.CharField(blank=True, max_length=50)),
                ('tipo_assinatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrativo.Assinatura')),
            ],
            options={
                'verbose_name': 'Usuário do Espaço',
                'verbose_name_plural': 'Usuários do Espaço',
            },
        ),
        migrations.CreateModel(
            name='UsuarioIntervalosHorarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_intervalos_horarios', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrativo.IntervalosHorarios')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios_meviro.UsuarioEspaco')),
            ],
            options={
                'verbose_name': 'Provável Horário de Uso',
                'verbose_name_plural': 'Prováveis Horários de Uso',
            },
        ),
        migrations.AddField(
            model_name='usuariodiassemana',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios_meviro.UsuarioEspaco'),
        ),
    ]
