# Generated by Django 2.1.5 on 2020-02-06 13:10

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infra', '0001_initial'),
        ('administrativo', '0001_initial'),
        ('educacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data para Reserva')),
                ('horario', models.CharField(choices=[('10:00-11:00', '10:00:00-11:00:00'), ('13:00-14:00', '13:00:00-14:00:00'), ('17:00-18:00', '17:00:00-18:00:00'), ('19:00-20:00', '19:00:00-20:00:00')], default='10:00-11:00', max_length=12, verbose_name='Horário da reserva')),
                ('recursos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='infra.Recurso', verbose_name='Recurso a ser reservado')),
            ],
        ),
        migrations.CreateModel(
            name='CreditoPorUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateField(blank=True, null=True, verbose_name='Data de Ativação')),
                ('data_encerramento', models.DateField(blank=True, null=True, verbose_name='Data de Encerramento')),
                ('id_venda_contaazul', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Venda ContaAzul')),
                ('numero_creditos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.Pacote', verbose_name='Pacote')),
            ],
            options={
                'verbose_name_plural': 'Créditos por Usuário',
                'verbose_name': 'Crédito por Usuário',
            },
        ),
        migrations.CreateModel(
            name='PacotePorUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=False, verbose_name='Este plano está ativo?')),
                ('data_ativacao', models.DateField(blank=True, null=True, verbose_name='Data de Ativação')),
                ('data_encerramento', models.DateField(blank=True, null=True, verbose_name='Data de Encerramento')),
                ('id_venda_contaazul', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Venda ContaAzul')),
                ('quantidade', models.IntegerField(blank=True, null=True, verbose_name='Quantidade')),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.Pacote', verbose_name='Pacote')),
            ],
            options={
                'verbose_name_plural': 'Pacotes por Usuário',
                'verbose_name': 'Pacote por Usuário',
            },
        ),
        migrations.CreateModel(
            name='UsuarioEspaco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=30, verbose_name='Primeiro nome')),
                ('sobrenome', models.CharField(max_length=200, verbose_name='Sobrenomes')),
                ('razao_visita', models.CharField(choices=[('reuniao', 'Reunião'), ('tour_agendado', 'Tour Agendado'), ('tour_nao_agendado', 'Tour não agendado'), ('visita_parceiro', 'Visita Parceiro'), ('curso_atividade', 'Participar de uma Atividade'), ('atividade_terceiros', 'Atividade de Terceiros'), ('visita_parceiro', 'Visita Parceiro'), ('uso_maquinas', 'Uso do Espaço'), ('outros', 'Outros')], max_length=30, null=True, verbose_name='Razão da Visita')),
                ('cpf', models.CharField(max_length=30, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=30, null=True, verbose_name='RG')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('interesses', multiselectfield.db.fields.MultiSelectField(choices=[('marcenaria', 'Marcenaria'), ('eletronica', 'Eletrônica'), ('impressao3D', 'Impressão 3D'), ('serralheria', 'Serralheria'), ('cortadora_laser', 'Cortarora Laser'), ('cnc', 'CNC'), ('cultura_maker', 'Cultura Maker'), ('atividades_impacto', 'Atividades de Impacto Socio Ambiental'), ('inclusao_pcds', 'Inclusão de PCDs')], default=None, max_length=112, verbose_name='Interesses')),
                ('endereco', models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço')),
                ('cidade', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='Estado')),
                ('telefone_celular', models.CharField(blank=True, max_length=30, null=True)),
                ('nome_contato_emergencia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do Contato de Emergência')),
                ('telefone_contato_emergencia', models.CharField(blank=True, max_length=30, verbose_name='Telefone do Contato de Emergência')),
                ('foto', models.ImageField(blank=True, upload_to='fotos_usuarios_espaco', verbose_name='Foto do usuário')),
                ('apelido', models.CharField(blank=True, max_length=30, null=True)),
                ('tem_plano_saude', models.BooleanField(default=False, verbose_name='Usuário possui plano de saúde')),
                ('nome_plano_saude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Qual o nome do plano de saúde?')),
                ('id_contaazul', models.CharField(blank=True, max_length=200, null=True, verbose_name='ID Conta Azul')),
                ('treinamentoEmEquipamentos', models.ManyToManyField(blank=True, to='educacao.TreinamentoEmEquipamento', verbose_name='Possui treinamento nos seguintes equipamentos')),
            ],
            options={
                'verbose_name_plural': 'Usuários do Espaço',
                'verbose_name': 'Usuário do Espaço',
            },
        ),
        migrations.AddField(
            model_name='pacoteporusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_meviro.UsuarioEspaco', verbose_name='Nome do Usuário'),
        ),
        migrations.AddField(
            model_name='creditoporusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_meviro.UsuarioEspaco', verbose_name='Nome do Usuário'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='usuarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios_meviro.UsuarioEspaco', verbose_name='Nome do Usuário'),
        ),
    ]
