# Generated by Django 2.1.5 on 2020-02-06 13:51

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_meviro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditoporusuario',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Este plano está ativo?'),
        ),
        migrations.AddField(
            model_name='usuarioespaco',
            name='habilidades',
            field=models.TextField(blank=True, null=True, verbose_name='Habilidades'),
        ),
        migrations.AddField(
            model_name='usuarioespaco',
            name='ocupacao_funcao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ocupação Profissional'),
        ),
        migrations.AddField(
            model_name='usuarioespaco',
            name='onde_trabalha',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Onde Trabalha'),
        ),
        migrations.AddField(
            model_name='usuarioespaco',
            name='para_quem_construir',
            field=models.CharField(blank=True, choices=[('propria', 'Para o próprio usuário.'), ('contratante', 'Para um contratante'), ('empregador', 'Para um empregador '), ('outros', 'Outros')], max_length=90, null=True, verbose_name='Para quem costuma construir?'),
        ),
        migrations.AlterField(
            model_name='usuarioespaco',
            name='interesses',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('marcenaria', 'Marcenaria'), ('eletronica', 'Eletrônica'), ('impressao3D', 'Impressão 3D'), ('serralheria', 'Serralheria'), ('cortadora_laser', 'Cortarora Laser'), ('cnc', 'CNC'), ('cultura_maker', 'Cultura Maker'), ('atividades_impacto', 'Atividades de Impacto Socio Ambiental'), ('inclusao_pcds', 'Inclusão de PCDs')], default=None, max_length=112, null=True, verbose_name='Interesses'),
        ),
    ]
