# Generated by Django 2.1.5 on 2019-06-21 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_meviro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioespaco',
            name='telefone_comercial',
        ),
        migrations.RemoveField(
            model_name='usuarioespaco',
            name='telefone_residencial',
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data',
            field=models.DateField(verbose_name='Data para Reserva'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='horario',
            field=models.CharField(choices=[('10:00-11:00', '10:00:00-11:00:00'), ('13:00-14:00', '13:00:00-14:00:00'), ('17:00-18:00', '17:00:00-18:00:00'), ('19:00-20:00', '19:00:00-20:00:00')], default='10:00-11:00', max_length=12, verbose_name='Horário da reserva'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='recursos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='infra.Recurso', verbose_name='Recurso a ser reservado'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='usuarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios_meviro.UsuarioEspaco', verbose_name='Nome do Usuário'),
        ),
        migrations.AlterField(
            model_name='usuarioespaco',
            name='apelido',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usuarioespaco',
            name='cidade',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='usuarioespaco',
            name='cpf',
            field=models.CharField(max_length=30, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='usuarioespaco',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='usuarioespaco',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='usuarioespaco',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='usuarioespaco',
            name='estado',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='usuarioespaco',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos_usuarios_espaco', verbose_name='Foto do usuário'),
        ),
        migrations.AlterField(
            model_name='usuarioespaco',
            name='nome_contato_emergencia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do Contato de Emergência'),
        ),
        migrations.AlterField(
            model_name='usuarioespaco',
            name='nome_plano_saude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Qual o nome do plano de saúde?'),
        ),
        migrations.AlterField(
            model_name='usuarioespaco',
            name='pacotes',
            field=models.ManyToManyField(to='administrativo.Pacote', verbose_name='Pacotes Assinados'),
        ),
        migrations.AlterField(
            model_name='usuarioespaco',
            name='primeiro_nome',
            field=models.CharField(max_length=30, verbose_name='Primeiro nome'),
        ),
        migrations.AlterField(
            model_name='usuarioespaco',
            name='rg',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='usuarioespaco',
            name='sobrenome',
            field=models.CharField(max_length=200, verbose_name='Sobrenomes'),
        ),
        migrations.AlterField(
            model_name='usuarioespaco',
            name='telefone_celular',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usuarioespaco',
            name='telefone_contato_emergencia',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefone do Contato de Emergência'),
        ),
        migrations.AlterField(
            model_name='usuarioespaco',
            name='tem_plano_saude',
            field=models.BooleanField(default=False, verbose_name='Usuário possui plano de saúde'),
        ),
        migrations.AlterField(
            model_name='usuarioespaco',
            name='treinamentoEmEquipamentos',
            field=models.ManyToManyField(to='educacao.TreinamentoEmEquipamento', verbose_name='Possui treinamento nos seguintes equipamentos'),
        ),
    ]
