# Generated by Django 2.1.5 on 2020-02-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_meviro', '0002_auto_20200206_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioespaco',
            name='indicacao_servicos',
            field=models.BooleanField(default=False, verbose_name='Gostaria de receber indicações para prestação de serviços'),
        ),
        migrations.AddField(
            model_name='usuarioespaco',
            name='interesse_educador',
            field=models.BooleanField(default=False, verbose_name='Tem interesse em ser educador no espaço'),
        ),
        migrations.AddField(
            model_name='usuarioespaco',
            name='outras_informacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Outras informações relevantes'),
        ),
        migrations.AddField(
            model_name='usuarioespaco',
            name='possivel_parceiro_pf',
            field=models.BooleanField(default=False, verbose_name='Possível parceiro Pessoa Física'),
        ),
        migrations.AddField(
            model_name='usuarioespaco',
            name='possivel_parceiro_pj',
            field=models.BooleanField(default=False, verbose_name='Possível parceiro Pessoa Jurídica'),
        ),
    ]
