# Generated by Django 2.1.5 on 2019-06-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_meviro', '0002_auto_20190621_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioespaco',
            name='contratos',
            field=models.ManyToManyField(blank=True, to='administrativo.Contrato'),
        ),
        migrations.AlterField(
            model_name='usuarioespaco',
            name='treinamentoEmEquipamentos',
            field=models.ManyToManyField(blank=True, to='educacao.TreinamentoEmEquipamento', verbose_name='Possui treinamento nos seguintes equipamentos'),
        ),
    ]
