# Generated by Django 2.1.5 on 2019-06-25 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_meviro', '0003_auto_20190622_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioespaco',
            name='contratos',
        ),
        migrations.RemoveField(
            model_name='usuarioespaco',
            name='pacotes',
        ),
    ]
