# Generated by Django 2.1.5 on 2019-08-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_meviro', '0005_creditoporusuario_pacoteporusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioespaco',
            name='id_contaazul',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ID Conta Azul'),
        ),
    ]
