# Generated by Django 2.1.5 on 2019-08-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_meviro', '0006_usuarioespaco_id_contaazul'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditoporusuario',
            name='id_venda',
        ),
        migrations.RemoveField(
            model_name='pacoteporusuario',
            name='id_venda',
        ),
        migrations.AddField(
            model_name='creditoporusuario',
            name='id_venda_contaazul',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Venda ContaAzul'),
        ),
        migrations.AddField(
            model_name='pacoteporusuario',
            name='id_venda_contaazul',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Venda ContaAzul'),
        ),
    ]
