# Generated by Django 2.1.5 on 2019-08-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_meviro', '0007_auto_20190810_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditoporusuario',
            name='data_compra',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Ativação'),
        ),
        migrations.AlterField(
            model_name='creditoporusuario',
            name='data_encerramento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Encerramento'),
        ),
    ]
