# Generated by Django 2.1.5 on 2019-08-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_meviro', '0008_auto_20190810_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacoteporusuario',
            name='data_ativacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Ativação'),
        ),
        migrations.AlterField(
            model_name='pacoteporusuario',
            name='data_encerramento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Encerramento'),
        ),
    ]
