# Generated by Django 2.1.5 on 2019-08-16 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_meviro', '0009_auto_20190810_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacoteporusuario',
            name='pacote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.Pacote', verbose_name='Pacote'),
        ),
        migrations.AlterField(
            model_name='pacoteporusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_meviro.UsuarioEspaco', verbose_name='Nome do Usuário'),
        ),
    ]
