# Generated by Django 2.1.5 on 2019-08-19 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_meviro', '0010_auto_20190815_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacoteporusuario',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='creditoporusuario',
            name='numero_creditos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.Pacote', verbose_name='Pacote'),
        ),
        migrations.AlterField(
            model_name='creditoporusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios_meviro.UsuarioEspaco', verbose_name='Nome do Usuário'),
        ),
    ]
