# Generated by Django 2.1.5 on 2019-08-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=200, null=True, verbose_name='Refresh Token')),
                ('refresh_token', models.CharField(blank=True, max_length=200, null=True, verbose_name='Refresh Token')),
                ('hora_atualizacao', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tokens',
                'verbose_name': 'Token',
            },
        ),
    ]
