# Generated by Django 2.1.5 on 2019-08-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contaazul', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Access Token'),
        ),
    ]
