# Generated by Django 2.1.5 on 2019-06-21 00:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precisa_treinamento', models.BooleanField(default=False)),
                ('nome', models.CharField(max_length=30)),
                ('dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), size=None)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='OutraAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), size=None)),
            ],
            options={
                'verbose_name': 'Outra Atividade',
                'verbose_name_plural': 'Outras Atividades',
            },
        ),
        migrations.CreateModel(
            name='TreinamentoEmEquipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurso', models.ManyToManyField(to='infra.Recurso')),
            ],
            options={
                'verbose_name': 'Treinamento em Equipamento',
                'verbose_name_plural': 'Treinamentos em Equipamentos',
            },
        ),
        migrations.AddField(
            model_name='outraatividade',
            name='treinamentoEmEquipamentos',
            field=models.ManyToManyField(to='educacao.TreinamentoEmEquipamento'),
        ),
        migrations.AddField(
            model_name='curso',
            name='treinamentoEmEquipamentos',
            field=models.ManyToManyField(to='educacao.TreinamentoEmEquipamento'),
        ),
    ]
