# Generated by Django 2.1.5 on 2019-06-21 18:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='descricao',
            field=models.TextField(null=True, verbose_name='Descrição do Curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='professores',
            field=models.TextField(null=True, verbose_name='Professores do Curso'),
        ),
        migrations.AddField(
            model_name='outraatividade',
            name='descricao',
            field=models.TextField(null=True, verbose_name='Descrição da Atividade'),
        ),
        migrations.AddField(
            model_name='outraatividade',
            name='organizadores',
            field=models.TextField(null=True, verbose_name='Organizadores da Atividade'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), size=None, verbose_name='Quais as datas do curso?'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome do Curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='precisa_treinamento',
            field=models.BooleanField(default=False, verbose_name='É necessário treinamento em equipamentos?'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='treinamentoEmEquipamentos',
            field=models.ManyToManyField(to='educacao.TreinamentoEmEquipamento', verbose_name='Em quais equipamentos?'),
        ),
        migrations.AlterField(
            model_name='outraatividade',
            name='dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), size=None, verbose_name='Quais as datas da atividade?'),
        ),
        migrations.AlterField(
            model_name='outraatividade',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome da Atividade'),
        ),
        migrations.AlterField(
            model_name='treinamentoemequipamento',
            name='recurso',
            field=models.ManyToManyField(to='infra.Recurso', verbose_name='Recurso utilizado no treinamento'),
        ),
    ]
