# Generated by Django 2.1.5 on 2019-06-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0002_auto_20190621_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='observacoes',
            field=models.TextField(null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='outraatividade',
            name='observacoes',
            field=models.TextField(null=True, verbose_name='Observações'),
        ),
    ]
