# Generated by Django 2.1.5 on 2019-06-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0003_auto_20190621_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outraatividade',
            name='treinamentoEmEquipamentos',
            field=models.ManyToManyField(to='educacao.TreinamentoEmEquipamento', verbose_name='Treinamento em Equipamentos'),
        ),
    ]
