# Generated by Django 2.1.5 on 2019-06-21 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=30)),
                ('codigo', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': 'Brigde',
                'verbose_name_plural': 'Brigdes',
            },
        ),
        migrations.CreateModel(
            name='BridgeAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_brigde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='infra.Bridge')),
            ],
            options={
                'verbose_name': 'Brigde <> Recurso',
                'verbose_name_plural': 'Brigdes <> Recursos',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=200)),
                ('site', models.CharField(max_length=70)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('telefone', models.CharField(max_length=30)),
                ('nome_contato', models.CharField(max_length=30)),
                ('email_contato', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_recurso', models.CharField(choices=[('Porta', 'porta'), ('Terminal Check-in/out', 'terminal check-in/out'), ('Sala', 'sala'), ('Bancada', 'bancada'), ('Maquina', 'maquina'), ('Ferramenta manual', 'ferramenta manual'), ('Ferramenta eletrica', 'ferramenta eletrica'), ('Ferramenta pneumatica', 'ferramenta pneumatica'), ('Material Insumo', 'material insumo')], max_length=30)),
                ('nome', models.CharField(help_text='Aqui vai um texto de ajuda mesmo.', max_length=30, verbose_name='Nome do Recurso')),
                ('apelido', models.CharField(max_length=30)),
                ('descricao', models.TextField(null=True)),
                ('fabricante', models.CharField(max_length=30)),
                ('data_aquisicao', models.DateField()),
                ('api_financeiro', models.CharField(max_length=30)),
                ('ultima_atualizacao', models.DateField(blank=True)),
                ('voltagem', models.CharField(choices=[('110v', '110'), ('220v', '220')], max_length=10)),
                ('amperagem', models.IntegerField(blank=True)),
                ('potencia', models.IntegerField(blank=True)),
                ('codigo_meviro', models.IntegerField(blank=True)),
                ('codigo_barra', models.CharField(max_length=256)),
                ('requer_treinamento', models.BooleanField(default=True)),
                ('requer_setup', models.BooleanField(default=True)),
                ('custo_hora', models.DecimalField(decimal_places=2, max_digits=6)),
                ('custo_integral', models.DecimalField(decimal_places=2, max_digits=6)),
                ('custo_credito', models.IntegerField(blank=True)),
                ('hora_max_dia_usuario', models.IntegerField(blank=True)),
                ('hora_max_sem_usuario', models.IntegerField(blank=True)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infra.Fornecedor')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
            },
        ),
        migrations.AddField(
            model_name='bridgeauth',
            name='id_recurso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='infra.Recurso'),
        ),
        migrations.AddField(
            model_name='bridge',
            name='recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='infra.Recurso'),
        ),
    ]
