# Generated by Django 2.1.5 on 2019-01-28 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrativo', '0001_initial'),
        ('usuarios_meviro', '0001_initial'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arduino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=30)),
                ('codigo', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': 'Arduino',
                'verbose_name_plural': 'Arduinos',
            },
        ),
        migrations.CreateModel(
            name='ArduinoAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_arduino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios_meviro.UsuarioEspaco')),
            ],
            options={
                'verbose_name': 'Arduino Auth',
                'verbose_name_plural': 'Arduinos Auth',
            },
        ),
        migrations.CreateModel(
            name='Armarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('apelido', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Armário',
                'verbose_name_plural': 'Armários',
            },
        ),
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
                ('fabricante', models.CharField(max_length=30)),
                ('data_aquisicao', models.DateField()),
                ('foto', models.ImageField(blank=True, upload_to='uploads/foto_ferramentas')),
                ('ferramenta_eletrica', models.BooleanField(default=True)),
                ('voltagem', models.CharField(blank=True, max_length=30)),
                ('amperagem', models.CharField(blank=True, max_length=30)),
                ('potencia', models.CharField(blank=True, max_length=30)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrativo.Fornecedor')),
            ],
            options={
                'verbose_name': 'Ferramenta',
                'verbose_name_plural': 'Ferramentas',
            },
        ),
        migrations.CreateModel(
            name='FuncaoFerramenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Função da Ferramenta',
                'verbose_name_plural': 'Função das Ferramentas',
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('apelido', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=200)),
                ('fabricante', models.CharField(max_length=30)),
                ('data_aquisicao', models.DateField()),
                ('data_ultima_manutencao', models.DateField()),
                ('descricao_ultima_manutencao', models.TextField(null=True)),
                ('foto', models.ImageField(blank=True, upload_to='uploads/foto_ferramentas')),
                ('voltagem', models.CharField(max_length=30)),
                ('amperagem', models.CharField(max_length=30)),
                ('potencia', models.CharField(max_length=30)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrativo.Fornecedor')),
                ('funcao_ferramenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infra.FuncaoFerramenta')),
                ('nota_fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.NotaFiscal')),
            ],
            options={
                'verbose_name': 'Ferramenta',
                'verbose_name_plural': 'Ferramentas',
            },
        ),
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
                ('localizacao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Seção',
                'verbose_name_plural': 'Seções',
            },
        ),
        migrations.AddField(
            model_name='maquina',
            name='secao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infra.Secao'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='funcao_ferramenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infra.FuncaoFerramenta'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='nota_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.NotaFiscal'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='secao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infra.Secao'),
        ),
        migrations.AddField(
            model_name='armarios',
            name='secao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infra.Secao'),
        ),
        migrations.AddField(
            model_name='arduinoauth',
            name='id_secao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='infra.Secao'),
        ),
    ]
