# Generated by Django 2.1.5 on 2019-06-21 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurso',
            name='codigo_barra',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='CNPJ do Fornecedor'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='bridge',
            name='codigo',
            field=models.CharField(blank=True, max_length=30, verbose_name='Código da Bridge'),
        ),
        migrations.AlterField(
            model_name='bridge',
            name='nome',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nome da Bridge'),
        ),
        migrations.AlterField(
            model_name='bridge',
            name='recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='infra.Recurso', verbose_name='Com qual recurso se conecta?'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='email_contato',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Fornecedor'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='estado',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome do Fornecedor'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome_contato',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='site',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='amperagem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='apelido',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='O recurso tem algum apelido?'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='codigo_meviro',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código Referência MeViro'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='custo_credito',
            field=models.IntegerField(blank=True, null=True, verbose_name='Custo de Uso por Crédito'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='custo_hora',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Custo de Uso por Hora'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='custo_integral',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Custo de Uso Integral'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='data_aquisicao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da aquisição'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='fabricante',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='hora_max_dia_usuario',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número máximo de horas de utilização por dia por usuário'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='hora_max_sem_usuario',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número máximo de horas de utilização por semana por usuário'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='potencia',
            field=models.IntegerField(blank=True, null=True, verbose_name='Potência'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='requer_setup',
            field=models.BooleanField(default=False, verbose_name='Requer algum setup inicial para o uso?'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='requer_treinamento',
            field=models.BooleanField(default=False, verbose_name='Requer treinamento para o uso?'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='tipo_recurso',
            field=models.CharField(choices=[('porta', 'Porta'), ('terminal check-in/out', 'Terminal Check-in/out'), ('sala', 'Sala'), ('bancada', 'Bancada'), ('maquina', 'Maquina'), ('ferramenta manual', 'Ferramenta Manual'), ('ferramenta eletrica', 'Ferramenta Elétrica'), ('ferramenta pneumatica', 'Ferramenta Pneumática'), ('material insumo', 'Material Insumo')], max_length=30),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='ultima_atualizacao',
            field=models.DateField(blank=True, null=True, verbose_name='Última atualização'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='voltagem',
            field=models.CharField(blank=True, choices=[('110v', '110'), ('220v', '220')], max_length=10, null=True),
        ),
    ]
