# Generated by Django 2.1.5 on 2019-01-28 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0002_auto_20190128_1150'),
        ('infra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecaoAssinatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_assinatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrativo.Assinatura')),
                ('id_secao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infra.Secao')),
            ],
            options={
                'verbose_name_plural': 'Relação - Assinaturas e Seções',
                'verbose_name': 'Relação - Assinatura e Seção',
            },
        ),
    ]
