# Generated by Django 2.1.5 on 2019-01-28 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0002_secaoassinatura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arduinoauth',
            options={'verbose_name': 'Arduino <> Seção', 'verbose_name_plural': 'Arduinos <> Seções'},
        ),
        migrations.AlterModelOptions(
            name='secaoassinatura',
            options={'verbose_name': 'Assinatura <> Seção', 'verbose_name_plural': 'Assinaturas <> Seções'},
        ),
    ]
