# Generated by Django 2.1.5 on 2020-02-06 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0002_auto_20200206_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=30, verbose_name='Nome da Área do Espaço')),
                ('codigo', models.CharField(blank=True, max_length=30, verbose_name='Código da Área')),
            ],
            options={
                'verbose_name_plural': 'Áreas do Espaço',
                'verbose_name': 'Área do Espaço',
            },
        ),
        migrations.AddField(
            model_name='recurso',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infra.Area'),
        ),
    ]
