# Generated by Django 2.1.5 on 2019-06-24 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0002_auto_20190621_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bridgeauth',
            name='id_brigde',
        ),
        migrations.RemoveField(
            model_name='bridgeauth',
            name='id_recurso',
        ),
        migrations.DeleteModel(
            name='BridgeAuth',
        ),
    ]
