# Generated by Django 2.1.5 on 2019-01-28 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0003_auto_20190128_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arduinoauth',
            name='id_arduino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='infra.Arduino'),
        ),
    ]
