# Generated by Django 2.1.5 on 2020-02-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0004_auto_20200206_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='link_instrucoes',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Link com Instruções de Uso'),
        ),
    ]
