# Generated by Django 2.1.5 on 2020-02-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0005_recurso_link_instrucoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='valor_aquisicao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Valor (R$) da Aquisição'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='valor_atual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Valor (R$) atual do Recurso'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='link_instrucoes',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Link com Instruções de uso'),
        ),
    ]
