# Generated by Django 2.1.5 on 2019-02-01 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0004_auto_20190128_1204'),
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logusoferramentausuario',
            name='id_ferramenta',
        ),
        migrations.AddField(
            model_name='logusoferramentausuario',
            name='id_arduino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='infra.Arduino'),
        ),
    ]
