# Generated by Django 2.1.5 on 2019-01-24 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_espaco', '0001_initial'),
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logusoferramentausuario',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='logusoferramentausuario',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios_espaco.UsuarioEspaco'),
        ),
    ]
