# Generated by Django 2.1.5 on 2019-01-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20190124_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='logusoferramentausuario',
            name='data_desativacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logusoferramentausuario',
            name='hora_desativacao',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logusoferramentausuario',
            name='data_ativacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logusoferramentausuario',
            name='hora_ativacao',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
