# Generated by Django 2.1.5 on 2019-01-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20190124_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logacessoespacousuario',
            name='data_entrada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logacessoespacousuario',
            name='data_saida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logacessoespacousuario',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logacessoespacousuario',
            name='hora_saida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
