# Generated by Django 2.1.5 on 2019-01-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_auto_20190124_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logusoferramentausuario',
            name='tempo_uso',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
