# Generated by Django 2.1.5 on 2019-01-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('data_implantacao', models.DateField()),
                ('ultima_atualizacao', models.DateField(blank=True)),
                ('valor', models.IntegerField(blank=True)),
                ('periodo', models.CharField(max_length=30)),
                ('observacao', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Assinatura',
            },
        ),
        migrations.CreateModel(
            name='DiasSemana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dia', models.IntegerField(default=0)),
                ('dia', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': '[fixo] Dias da Semana',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=200)),
                ('site', models.CharField(max_length=70)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('telefone', models.CharField(max_length=30)),
                ('nome_contato', models.CharField(max_length=30)),
                ('email_contato', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='IntervalosHorarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalo', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': '[fixo] Intervalos de Horários',
            },
        ),
    ]
