# Generated by Django 2.1.5 on 2020-02-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infra', '0001_initial'),
        ('educacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome do Contrato')),
                ('arquivo', models.ImageField(upload_to='arquivos/contratos', verbose_name='Arquivo do Contrato')),
                ('descricao', models.TextField(null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name_plural': 'Contratos',
                'verbose_name': 'Contrato',
            },
        ),
        migrations.CreateModel(
            name='OutrosProdutos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome do Produto')),
            ],
        ),
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Pacote de Assinaturas, Cursos ou Outras Atividades.', max_length=60, verbose_name='Nome do Pacote')),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor de Venda')),
                ('valor_custo', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor de Custo')),
                ('codigo', models.CharField(blank=True, default='MV_ADMIN', max_length=50, null=True, verbose_name='Código')),
                ('descricao', models.TextField(null=True, verbose_name='Descrição do Pacote')),
                ('data_implantacao', models.DateField(null=True, verbose_name='Data da Implantação')),
                ('ultima_atualizacao', models.DateField(blank=True, null=True, verbose_name='Data da Última Atualização')),
                ('numero_credito', models.IntegerField(blank=True, null=True, verbose_name='Número de créditos disponíveis')),
                ('tipo_periodo_minimo', models.CharField(blank=True, choices=[('Horas', 'horas'), ('Dias', 'dias'), ('Semanas', 'semanas'), ('Meses', 'meses')], help_text='Dias, Semanas, Meses', max_length=256, null=True, verbose_name='Período Mínimo')),
                ('valor_periodo_minimo', models.IntegerField(blank=True, null=True, verbose_name='Quantidade Período Mínimo')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('pode_agendar_maquinas', models.BooleanField(default=False, verbose_name='Pode realizar agendamentos?')),
                ('assinantes_tem_desconto_recurso', models.BooleanField(default=False, verbose_name='Assinantes tem desconto para utilização dos recursos?')),
                ('desconto_recurso_percentual', models.IntegerField(blank=True, null=True, verbose_name='Desconto percentual por recurso')),
                ('desconto_recurso_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Desconto integral por recurso')),
                ('id_contaazul', models.CharField(blank=True, max_length=200, null=True, verbose_name='ID Conta Azul')),
                ('contrato', models.ManyToManyField(blank=True, to='administrativo.Contrato', verbose_name='Contratos')),
                ('curso', models.ManyToManyField(blank=True, to='educacao.Curso', verbose_name='Algum curso relacionado?')),
                ('outraAtividade', models.ManyToManyField(blank=True, to='educacao.OutraAtividade', verbose_name='Alguma outra atividade relacionada?')),
            ],
            options={
                'verbose_name_plural': 'Pacotes',
                'verbose_name': 'Pacote',
            },
        ),
        migrations.CreateModel(
            name='PeriodosReservaRecurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Períodos para Resevas',
                'verbose_name': 'Período para Reseva',
            },
        ),
        migrations.CreateModel(
            name='Regra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodosReservaRecurso', models.ManyToManyField(to='administrativo.PeriodosReservaRecurso', verbose_name='Quando?')),
                ('recurso', models.ManyToManyField(to='infra.Recurso', verbose_name='Garante acesso ao seguinte recurso:')),
            ],
            options={
                'verbose_name_plural': 'Regras de Uso (Máquina por Período)',
                'verbose_name': 'Regra de Uso',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=254, verbose_name='Nome do Serviço')),
            ],
        ),
        migrations.AddField(
            model_name='pacote',
            name='regra',
            field=models.ManyToManyField(to='administrativo.Regra', verbose_name='Regras para utilização de recursos'),
        ),
    ]
