# Generated by Django 2.1.5 on 2020-02-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacote',
            name='is_responsavel',
            field=models.BooleanField(default=False, verbose_name='É responsável por alguém que usara o espaço?'),
        ),
        migrations.AddField(
            model_name='pacote',
            name='responsavel_por',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Reponsável por'),
        ),
    ]
