# Generated by Django 2.1.5 on 2019-01-28 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assinatura',
            options={'verbose_name': 'Tipo de Assinatura', 'verbose_name_plural': 'Tipos de Assinatura'},
        ),
    ]
