# Generated by Django 2.1.5 on 2019-06-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0002_auto_20190621_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notafiscal',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='pacote',
            name='horas_por_credito',
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='descricao',
            field=models.CharField(max_length=50, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='pacote',
            name='numero_credito',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de créditos disponíveis'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='arquivo',
            field=models.ImageField(upload_to='arquivos/contratos', verbose_name='Arquivo do Contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='descricao',
            field=models.TextField(null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome do Contrato'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='identificacao',
            field=models.CharField(max_length=50, verbose_name='Identificação'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='assinantes_tem_desconto_recurso',
            field=models.BooleanField(default=False, verbose_name='Assinantes tem desconto para utilização dos recursos?'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='contrato',
            field=models.ManyToManyField(to='administrativo.Contrato', verbose_name='Contratos'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='curso',
            field=models.ManyToManyField(to='educacao.Curso', verbose_name='Algum curso relacionado?'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='data_implantacao',
            field=models.DateField(verbose_name='Data da Implantação'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='desconto_recurso_percentual',
            field=models.IntegerField(blank=True, verbose_name='Desconto percentual por recurso'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='desconto_recurso_valor',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Desconto integral por recurso'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='descricao',
            field=models.TextField(verbose_name='Descrição do Pacote'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='nome',
            field=models.CharField(help_text='Pacote de Assinaturas, Cursos ou Outras Atividades.', max_length=60, verbose_name='Nome do Pacote'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='outraAtividade',
            field=models.ManyToManyField(to='educacao.OutraAtividade', verbose_name='Alguma outra atividade relacionada?'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='pode_agendar_maquinas',
            field=models.BooleanField(default=False, verbose_name='Pode realizar agendamentos?'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='regra',
            field=models.ManyToManyField(to='administrativo.Regra', verbose_name='Regras para utilização de recursos'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='tipo_periodo_minimo',
            field=models.CharField(blank=True, choices=[('Horas', 'horas'), ('Dias', 'dias'), ('Semanas', 'semanas'), ('Meses', 'meses')], help_text='Dias, Semanas, Meses', max_length=256, verbose_name='Período Mínimo'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='ultima_atualizacao',
            field=models.DateField(blank=True, verbose_name='Data da Última Atualização'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='valor_periodo_minimo',
            field=models.IntegerField(blank=True, verbose_name='Quantidade Período Mínimo'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='valor_recorrente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, verbose_name='Valor para cobrança recorrente'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='valor_unico',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, verbose_name='Valor para cobrança única'),
        ),
        migrations.AlterField(
            model_name='regra',
            name='periodosReservaRecurso',
            field=models.ManyToManyField(to='administrativo.PeriodosReservaRecurso', verbose_name='Quando?'),
        ),
        migrations.AlterField(
            model_name='regra',
            name='recurso',
            field=models.ManyToManyField(to='infra.Recurso', verbose_name='Garante acesso ao seguinte recurso:'),
        ),
    ]
