# Generated by Django 2.1.5 on 2019-06-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0003_auto_20190621_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacote',
            name='data_implantacao',
            field=models.DateField(null=True, verbose_name='Data da Implantação'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='desconto_recurso_percentual',
            field=models.IntegerField(blank=True, null=True, verbose_name='Desconto percentual por recurso'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='desconto_recurso_valor',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Desconto integral por recurso'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='descricao',
            field=models.TextField(null=True, verbose_name='Descrição do Pacote'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='regra',
            field=models.ManyToManyField(null=True, to='administrativo.Regra', verbose_name='Regras para utilização de recursos'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='tipo_periodo_minimo',
            field=models.CharField(blank=True, choices=[('Horas', 'horas'), ('Dias', 'dias'), ('Semanas', 'semanas'), ('Meses', 'meses')], help_text='Dias, Semanas, Meses', max_length=256, null=True, verbose_name='Período Mínimo'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='ultima_atualizacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Última Atualização'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='valor_periodo_minimo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade Período Mínimo'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='valor_recorrente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Valor para cobrança recorrente'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='valor_unico',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Valor para cobrança única'),
        ),
    ]
