# Generated by Django 2.1.5 on 2019-06-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0004_auto_20190621_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacote',
            name='regra',
            field=models.ManyToManyField(to='administrativo.Regra', verbose_name='Regras para utilização de recursos'),
        ),
    ]
