# Generated by Django 2.1.5 on 2019-06-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0005_auto_20190621_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='regra',
            name='nome',
            field=models.CharField(max_length=60, null=True, verbose_name='Nome da Regra'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='contrato',
            field=models.ManyToManyField(blank=True, to='administrativo.Contrato', verbose_name='Contratos'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='curso',
            field=models.ManyToManyField(blank=True, to='educacao.Curso', verbose_name='Algum curso relacionado?'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='desconto_recurso_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Desconto integral por recurso'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='outraAtividade',
            field=models.ManyToManyField(blank=True, to='educacao.OutraAtividade', verbose_name='Alguma outra atividade relacionada?'),
        ),
    ]
