# Generated by Django 2.1.5 on 2019-06-24 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0006_auto_20190622_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notafiscal',
            name='fornecedor',
        ),
        migrations.AlterModelOptions(
            name='regra',
            options={'verbose_name': 'Regra de Uso', 'verbose_name_plural': 'Regras de Uso (Máquina por Período)'},
        ),
        migrations.RemoveField(
            model_name='regra',
            name='nome',
        ),
        migrations.DeleteModel(
            name='NotaFiscal',
        ),
    ]
