# Generated by Django 2.1.5 on 2019-08-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0008_outrosprodutos_servico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacote',
            name='valor_recorrente',
        ),
        migrations.RemoveField(
            model_name='pacote',
            name='valor_unico',
        ),
        migrations.AddField(
            model_name='pacote',
            name='codigo',
            field=models.CharField(blank=True, default='PACOTE_MV_ADMIN', max_length=50, null=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='pacote',
            name='id_contaazul',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ID Conta Azul'),
        ),
        migrations.AddField(
            model_name='pacote',
            name='valor_custo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Valor de Custo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacote',
            name='valor_venda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Valor de Venda'),
            preserve_default=False,
        ),
    ]
