# Generated by Django 2.1.5 on 2019-08-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0009_auto_20190809_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacote',
            name='codigo',
            field=models.CharField(blank=True, default='MV_ADMIN', max_length=50, null=True, verbose_name='Código'),
        ),
    ]
