# Generated by Django 2.1.5 on 2019-01-24 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('apelido', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Armários',
                'verbose_name': 'Armário',
            },
        ),
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
                ('apelido', models.CharField(max_length=30)),
                ('fabricante', models.CharField(max_length=30)),
                ('data_aquisicao', models.DateField()),
                ('foto', models.ImageField(blank=True, upload_to='uploads/foto_ferramentas')),
                ('voltagem', models.CharField(max_length=30)),
                ('amperagem', models.CharField(max_length=30)),
                ('potencia', models.CharField(max_length=30)),
                ('numero_controle', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Ferramentas',
                'verbose_name': 'Ferramenta',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=200)),
                ('site', models.CharField(max_length=70)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('telefone', models.CharField(max_length=30)),
                ('nome_contato', models.CharField(max_length=30)),
                ('email_contato', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Fornecedores',
                'verbose_name': 'Fornecedor',
            },
        ),
        migrations.CreateModel(
            name='FuncaoFerramenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Função das Ferramentas',
                'verbose_name': 'Função da Ferramenta',
            },
        ),
        migrations.CreateModel(
            name='IndiceAlerta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice_alerta', models.IntegerField()),
                ('descricao', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': '[fixo] Índices de Alertas',
                'verbose_name': 'Índice de Alerta',
            },
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ferramentas.Fornecedor')),
            ],
            options={
                'verbose_name_plural': 'Notas Fiscais',
                'verbose_name': 'Nota Fiscal',
            },
        ),
        migrations.CreateModel(
            name='Riscos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
                ('alerta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ferramentas.IndiceAlerta')),
            ],
            options={
                'verbose_name_plural': 'Riscos',
                'verbose_name': 'Risco',
            },
        ),
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
                ('localizacao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Seções',
                'verbose_name': 'Seção',
            },
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ferramentas.Fornecedor'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='funcao_ferramenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ferramentas.FuncaoFerramenta'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='nota_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ferramentas.NotaFiscal'),
        ),
        migrations.AddField(
            model_name='armarios',
            name='secao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ferramentas.Secao'),
        ),
    ]
